# Site settings
title: devL
description: A blog about nothing
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joel Developer
user_description: wait..
user_title: Software Developer
email: joelweon@gmail.com
twitter_username: joelweon
github_username:  joelweon
gplus_username:  joelweon

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
